DE = [
    "Change your profile picture to a picture of a famous celebrity for 24 hours.",
    "Send a voice message saying 'I love pickles' to a group chat.",
    "Share the most embarrassing childhood photo of yourself.",
    "Send a message to a random contact and say, 'I'm a potato'.",
    "Change your WhatsApp status to 'I'm secretly a unicorn' for a day.",
    "Share a funny GIF and ask your friends to caption it.",
    "Create a TikTok video imitating your favorite movie character.",
    "Send a virtual 'air hug' to a friend in a private message.",
    "Share your best dad joke with a group chat.",
    "Change your Twitter profile picture to a cartoon character.",
    "Share a screenshot of your most recently used emojis.",
    "Record a video of you trying to lick your elbow and post it on Instagram.",
    "Send a message to a friend saying, 'Guess what I had for breakfast: pizza!'.",
    "Change your Facebook cover photo to a picture of your favorite food.",
    "Share a funny meme and ask your friends to rate it.",
    "Create a dance video on Instagram reels with a silly dance move.",
    "Send a virtual 'birthday cake' to a friend and wish them a happy birthday (even if it's not their birthday).",
    "Share a screenshot of your phone's home screen, revealing your apps.",
    "Record a video of you telling a joke and post it on Snapchat.",
    "Change your Instagram bio to something hilarious for 24 hours.",
    "Share a picture of you attempting to balance a spoon on your nose.",
    "Send a message to a friend with a random animal noise recording.",
    "Share a funny YouTube video and ask your friends to comment with their favorite part.",
    "Create a 'fun fact of the day' post on your social media.",
    "Change your WhatsApp display name to a funny pun.",
    "Share a screenshot of your most embarrassing autocorrect fail.",
    "Send a virtual 'thumbs up' to someone who deserves it.",
    "Share a picture of you wearing socks on your hands and trying to eat with them.",
    "Post a selfie with the silliest Snapchat filter you can find.",
    "Change your Twitter header to a picture of a cute animal.",
    "Share a funny riddle and see who can solve it the fastest.",
    "Create a TikTok video attempting a magic trick (even if it fails).",
    "Send a message to a friend saying, 'I'm starting a llama fan club, and you're the first member'.",
    "Share a screenshot of your most recently played mobile game.",
    "Change your Facebook relationship status to 'In a relationship with pizza'.",
    "Send a virtual 'cup of coffee' to a friend and ask how their day is going.",
    "Share a picture of you wearing a pair of underwear on your head.",
    "Record a video of you dancing to a silly song and post it on Instagram.",
    "Change your Instagram story highlight cover to a funny emoji.",
    "Share a screenshot of your most recently watched Netflix show.",
    "Send a message to a friend with a funny tongue twister.",
    "Post a selfie with a bizarre Snapchat filter and ask your friends to join in.",
    "Change your WhatsApp status to 'I'm on a secret mission' for a day.",
    "Share a funny quote and ask your friends if they agree.",
    "Create a TikTok video imitating your favorite cartoon character's voice.",
    "Send a virtual 'thumbs down' to something you dislike.",
    "Share a picture of your 'work from home' setup, no matter how messy it is.",
    "Record a video of you attempting to juggle random objects and post it on Snapchat.",
    "Change your Twitter profile picture to a funny meme.",
    "Share a screenshot of your most embarrassing text conversation.",
    "Send a message to a friend saying, *I just found out I can't touch my nose with my tongue.*",
    "Create a dance video on TikTok using a silly dance challenge.",
    "Share a picture of you attempting to do a handstand.",
    "Change your Facebook cover photo to a picture of your favorite movie scene.",
    "Post a selfie with a hilarious Instagram filter.",
    "Send a virtual *confetti explosion* to someone for achieving something small.",
    "Share a funny pun and ask your friends to come up with their own.",
    "Create a TikTok video trying to imitate a famous celebrity's voice.",
    "Send a message to a friend saying, *I just saw a UFO outside my window!*",
    "Change your WhatsApp status to *I'm officially a ninja* for a day.",
    "Share a screenshot of your most recently played mobile app game.",
    "Record a video of you attempting to do the moonwalk and post it on Instagram.",
    "Change your Instagram bio to a humorous poem.",
    "Send a message to a friend with a random joke.",
    "Share a picture of you attempting to make the silliest face possible.",
    "Create a dance video on Instagram reels using a silly filter.",
    "Send a virtual *applause* to someone who did something impressive.",
    "Share a funny YouTube blooper video and ask your friends to share their favorite parts.",
    "Change your Twitter header to a picture of a funny caricature of yourself.",
    "Post a selfie with a quirky Snapchat filter and encourage your friends to do the same.",
    "Send a message to a friend saying, *I just won a hotdog eating contest!*",
    "Change your Facebook relationship status to *Married to pizza.*",
    "Share a screenshot of your most recently read book or eBook.",
    "Record a video of you attempting to sing a song in a funny voice and post it on Snapchat.",
    "Change your Instagram story highlight icons to something goofy.",
    "Send a virtual *virtual reality headset* to a friend and ask them to describe their virtual adventures.",
    "Share a picture of you wearing a paper crown and pretending to be royalty.",
    "Create a TikTok video trying to impersonate a famous cartoon character.",
    "Send a message to a friend saying, *I just discovered a hidden treasure in my backyard!*",
    "Change your WhatsApp status to *I'm the master of invisibility* for a day.",
    "Share a screenshot of your most recently played online game.",
    "Record a video of you attempting to tell a funny bedtime story and post it on Instagram.",
    "Change your Twitter profile picture to a hilarious caricature of yourself.",
    "Post a selfie with a wacky Snapchat filter and challenge your friends to do the same.",
    "Send a message to a friend saying, *I just saw a dinosaur walking down the street!*",
    "Change your Facebook cover photo to a picture of your dream vacation destination.",
    "Share a screenshot of your most embarrassing social media post.",
    "Record a video of you attempting to impersonate a famous celebrity and post it on Snapchat.",
    "Change your Instagram bio to a whimsical joke.",
    "Send a message to a friend with a random tongue twister.",
    "Share a funny meme and ask your friends to create their own memes.",
    "Create a dance video on TikTok using a trendy dance challenge.",
    "Send a virtual *taco* to a friend and ask them to describe their dream taco.",
    "Share a picture of you wearing sunglasses indoors and pretending to be a celebrity.",
    "Record a video of you attempting to do a cartwheel and post it on Instagram.",
    "Change your WhatsApp status to *I'm currently on a mission to find Bigfoot* for a day.",
    "Share a screenshot of your most recently watched comedy show or stand-up special.",
    "Send a message to a friend saying, *I just saw a UFO again!*",
    "Change your Twitter profile picture to a funny cartoon character.",
    "Post a selfie with a goofy Instagram filter and challenge your friends to do the same.",
]


DH = [
    "24 ghante ke lie apanee profail tasveer ko kisee prasiddh selibritee kee tasveer mein badalen.",
    "samooh chait mein mujhe achaar pasand hai kahate hue ek dhvani sandesh bhejen.",
    "apane bachapan kee sabase sharmanaak tasveer saajha karen.",
    "kisee yaadrchchhik sampark ko ek sandesh bhejen aur kahen, main ek aaloo hoon.",
    "ek din ke lie apane vhaatsep stetas ko main gupt roop se ek yoonikorn hoon mein badalen.",
    "ek mazedaar gif saajha karen aur apane doston se ise kaipshan dene ke lie kahen.",
    "apane pasandeeda philm charitr kee nakal karate hue ek tikatok veediyo banaen.",
    "ek nijee sandesh mein kisee mitr ko varchual eyar hag bhejen.",
    "samooh chait ke saath apana sarvashreshth pita chutakula saajha karen.",
    "apane tvitar profail chitr ko kaartoon charitr mein badalen.",
    "apane sabase haal hee mein upayog kie gae imojee ka skreenashot saajha karen.",
    "apanee kohanee chaatane kee koshish karate hue ek veediyo rikord karen aur ise instaagraam par post karen.",
    "kisee mitr ko yah kahate hue sandesh bhejen, andaaja lagaen ki mainne naashte mein kya khaaya: pizza!.",
    "apane phesabuk kavar foto ko apane pasandeeda bhojan kee tasveer mein badalen.",
    "ek mazedaar meem saajha karen aur apane doston se ise ret karane ke lie kahen.",
    "ek moorkhataapoorn daans moov ke saath instaagraam reels par ek daans veediyo banaen.",
    "kisee mitr ko varchual janmadin ka kek bhejen aur unhen janmadin kee shubhakaamanaen den (bhale hee vah unaka janmadin na ho)",
    "apane aips ka khulaasa karate hue apane fon kee hom skreen ka skreenashot saajha karen.",
    "ek chutakula sunaate hue apana ek veediyo rikord karen aur ise snaipachait par post karen.",
    "apane instaagraam baayo ko 24 ghanton ke lie kisee manoranjak cheez mein badalen.",
    "apanee naak par chammach ko santulit karane ka prayaas karate hue apanee ek tasveer saajha karen.",
    "kisee yaadrchchhik pashu shor rikording ke saath kisee mitr ko ek sandesh bhejen.",
    "ek mazedaar youtubai veediyo saajha karen aur apane doston se unake pasandeeda bhaag par tippanee karane ke lie kahen.",
    "apane soshal meediya par ek din ka mazedaar tathy post banaen.",
    "apane vhaatsep disple naam ko ek ajeeb vaaky mein badalen.",
    "apanee sabase sharmanaak svat: sudhaar viphalata ka skreenashot saajha karen.",
    "kisee aise vyakti ko varchual thams ap bhejen jo isaka hakadaar ho.",
    "apane haathon mein moze pahane hue aur unake saath khaane kee koshish karate hue apanee ek tasveer saajha karen.",
    "sabase moorkhataapoorn snaipachait filtar jo aap pa sakate hain, ke saath ek selphee post karen.",
    "apane tvitar hedar ko ek pyaare jaanavar kee tasveer mein badalen.",
    "ek mazedaar pahelee saajha karen aur dekhen ki kaun ise sabase tezee se hal kar sakata hai.",
    "jaaduee trik ka prayaas karate hue ek tikatok veediyo banaen (bhale hee vah viphal ho jae)",
    "kisee mitr ko yah kahate hue sandesh bhejen, main ek laama phain klab shuroo kar raha hoon, aur aap pahale sadasy hain.",
    "apane sabase haal hee mein khele gae mobail gem ka skreenashot saajha karen.",
    "apane phesabuk rileshanaship stetas ko pijja ke saath rishte mein mein badalen.",
    "kisee mitr ko varchual kophee ka kap bhejen aur poochhen ki unaka din kaisa gujar raha hai.",
    "apane sir par andaraviyar pahane hue apanee ek tasveer saajha karen.",
    "kisee moorkhataapoorn gaane par naachate hue apana ek veediyo rikord karen aur ise instaagraam par post karen.",
    "apanee instaagraam storee hailait kavar ko ek mazedaar imojee mein badalen.",
    "apane sabase haal hee mein dekhe gae netaphliks sho ka skreenashot saajha karen.",
    "kisee mitr ko majaakiya bhaasha mein sandesh bhejen.",
    "ek vichitr snaipachait filtar ke saath ek selphee post karen aur apane doston ko isamen shaamil hone ke lie kahen.",
    "ek din ke lie apane vhaatsep stetas ko main ek gupt mishan par hoon mein badalen.",
    "ek mazedaar uddharan saajha karen aur apane doston se poochhen ki kya ve sahamat hain.",
    "apane pasandeeda kaartoon charitr kee aavaaz kee nakal karate hue ek tikatok veediyo banaen.",
    "aapako jo cheez naapasand hai us par aabhaasee angoothe neeche bhejen.",
    "apane ghar se kaam setap kee ek tasveer saajha karen, chaahe vah kitana bhee ganda kyon na ho.",
    "yaadrchchhik vastuon ko hathiyaane ka prayaas karate hue apana ek veediyo rikord karen aur ise snaipachait par post karen.",
    "apane tvitar profail chitr ko ek mazedaar meem mein badalen.",
    "apane sabase sharmanaak tekst vaartaalaap ka skreenashot saajha karen.",
    "kisee mitr ko yah kahate hue sandesh bhejen, *mujhe abhee pata chala ki main apanee jeebh se apanee naak nahin chhoo sakata.*",
    "ek moorkhataapoorn nrty chunautee ka upayog karake tikatok par ek nrty veediyo banaen.",
    "haindastaind karane ka prayaas karate hue apanee ek tasveer saajha karen.",
    "apane phesabuk kavar foto ko apane pasandeeda philm drshy kee tasveer mein badalen.",
    "ek praphullit karane vaale instaagraam philtar ke saath ek selphee post karen.",
    "kuchh chhota haasil karane ke lie kisee ko ek aabhaasee *kamfetee visphot* bhejen.",
    "ek ajeeb vaaky saajha karen aur apane doston se apana khud ka vaaky banaane ke lie kahen.",
    "kisee prasiddh selibritee kee aavaaz kee nakal karane ka prayaas karate hue ek tikatok veediyo banaen.",
    "kisee mitr ko yah kahate hue sandesh bhejen, *mainne abhee-abhee apanee khidakee ke baahar ek yooepho dekha!*",
    "ek din ke lie apane vhaatsep stetas ko *main aadhikaarik taur par ninja hoon* mein badalen.",
    "apane sabase haal hee mein khele gae mobail aip gem ka skreenashot saajha karen.",
    "moonavok karane ka prayaas karate hue apana ek veediyo rikord karen aur ise instaagraam par post karen.",
    "apane instaagraam baayo ko ek haasy kavita mein badalen.",
    "kisee mitr ko ek yaadrchchhik chutakule ke saath ek sandesh bhejen.",
    "sabase moorkhataapoorn chehare ko sambhav banaane ka prayaas karate hue apanee ek tasveer saajha karen.",
    "ek moorkhataapoorn filtar ka upayog karake instaagraam reels par ek nrty veediyo banaen.",
    "kisee aise vyakti ko aabhaasee *taaliyaan* bhejen jisane kuchh prabhaavashaalee kiya ho.",
    "ek mazedaar youtubai bloopar veediyo saajha karen aur apane doston se unake pasandeeda bhaag saajha karane ke lie kahen.",
    "apane tvitar hedar ko apane majaakiya kairikechar kee tasveer mein badalen.",
    "anoothe snaipachait filtar ke saath ek selphee post karen aur apane doston ko bhee aisa karane ke lie protsaahit karen.",
    "kisee mitr ko yah kahate hue sandesh bhejen, *mainne abhee-abhee hotadog khaane kee pratiyogita jeetee hai!*",
    "apane phesabuk rileshanaship stetas ko *mairid too pizza* mein badalen.",
    "apanee sabase haal hee mein padhee gaee kitaab ya eebuk ka skreenashot saajha karen.",
    "majaakiya aavaaz mein gaana gaane ka prayaas karate hue apana ek veediyo rikord karen aur ise snaipachait par post karen."
    "apane instaagraam storee hailait aaikan ko kuchh naasamajhee mein badalen.",
    "kisee mitr ko ek varchual *varchual riyalitee hedaset* bhejen aur unase apane aabhaasee kaaranaamon ka varnan karane ke lie kahen.",
    "kaagaz ka mukut pahane hue aur raajasee hone ka dikhaava karate hue apanee ek tasveer saajha karen.",
    "ek prasiddh kaartoon charitr ka pratiroopan karane ka prayaas karate hue ek tikatok veediyo banaen.",
    "ek mitr ko yah kahate hue sandesh bhejen, *mainne abhee-abhee apane pichhavaade mein ek chhipa hua khajaana khoja hai!*",
    "ek din ke lie apane vhaatsep stetas ko *main adrshyata ka svaamee hoon* mein badalen.",
    "apane sabase haal hee mein khele gae onalain gem ka skreenashot saajha karen.",
    "sote samay ek mazedaar kahaanee bataane ka prayaas karate hue apana ek veediyo rikord karen aur ise instaagraam par post karen.",
    "apane tvitar profail chitr ko svayan ke ek praphullit karane vaale kairikechar mein badalen.",
    "ek ajeeb snaipachait filtar ke saath ek selphee post karen aur apane doston ko bhee aisa karane ke lie chunautee den.",
    "apane mitr ko yah kahate hue sandesh bhejen, *mainne abhee ek daayanaasor ko sadak par chalate dekha!*",
    "apane phesabuk kavar foto ko apane sapanon ke avakaash gantavy kee tasveer mein badalen.",
    "apane sabase sharmanaak soshal meediya post ka skreenashot saajha karen.",
    "ek prasiddh selibritee ka roop dhaaran karane ka prayaas karate hue apana ek veediyo rikord karen aur ise snaipachait par post karen.",
    "apane instaagraam baayo ko ek manamaujee majaak mein badalen.",
    "kisee mitr ko bina soche-samajhe jeebh ghumaakar sandesh bhejen.",
    "ek mazedaar meem saajha karen aur apane doston se apane svayan ke meem banaane ke lie kahen.",
    "trendee daans chailenj ka upayog karake tikatok par ek daans veediyo banaen.",
    "kisee mitr ko varchual *taiko* bhejen aur unase apane sapanon ke taiko ka varnan karane ke lie kahen.",
    "ghar ke andar dhoop ka chashma pahane hue aur ek selibritee hone ka dikhaava karate hue apanee ek tasveer saajha karen.",
    "kaartavheel karane ka prayaas karate hue apana ek veediyo rikord karen aur ise instaagraam par post karen.",
    "apane vhaatsep stetas ko *main vartamaan mein ek din ke lie bigaphut khojane ke mishan par hoon* mein badalen.",
    "apane sabase haal hee mein dekhe gae komedee sho ya staind-ap speshal ka skreenashot saajha karen.",
    "kisee mitr ko yah kahate hue sandesh bhejen, *mainne abhee phir se ek yooepho dekha!*",
    "apane tvitar profail chitr ko ek mazedaar kaartoon charitr mein badalen.",
    "ek naasamajh instaagraam filtar ke saath ek selphee post karen aur apane doston ko bhee aisa karane ke lie chunautee den.",
]


TE = [
    "Have you ever accidentally sent a text to the wrong person?",
    "What's the silliest thing you've done while on a video call?",
    "Have you ever been caught laughing at a meme in a serious meeting?",
    "What's your go-to dance move when no one's watching?",
    "Have you ever snorted while laughing?",
    "What's the weirdest food combination you enjoy?",
    "Have you ever sung in the shower and pretended you were in a music video?",
    "What's the most embarrassing autocorrect fail you've had?",
    "Have you ever laughed so hard you cried?",
    "What's the strangest dream you've ever had?",
    "Have you ever tried to take a selfie with a celebrity cutout?",
    "What's the funniest movie or TV show you've ever watched?",
    "Have you ever worn your clothes inside out by mistake?",
    "What's the most ridiculous fashion trend you've followed?",
    "Have you ever pretended to know a song when you had no clue about the lyrics?",
    "What's the most awkward encounter you've had with a stranger?",
    "Have you ever accidentally liked an old photo while stalking someone on social media?",
    "What's the funniest YouTube video you've ever seen?",
    "Have you ever laughed at a joke you didn't understand just to fit in?",
    "What's the silliest thing you believed as a child?",
    "Have you ever laughed so hard that you couldn't breathe?",
    "What's the most embarrassing thing you've done in front of your crush?",
    "Have you ever sent a text to your crush by mistake?",
    "What's the most embarrassing nickname you've had?",
    "Have you ever laughed at something inappropriate during a serious moment?",
    "What's the strangest talent you have?",
    "Have you ever tripped and fallen in public?",
    "What's the funniest animal video you've seen online?",
    "Have you ever tried to imitate a celebrity's accent?",
    "What's the most embarrassing thing in your browser history?",
    "Have you ever laughed during a serious argument?",
    "What's the weirdest habit you have when you're alone?",
    "Have you ever accidentally insulted someone without realizing it?",
    "What's the funniest word you know?",
    "Have you ever had a funny encounter with a stranger on public transportation?",
    "What's the oddest thing you collect?",
    "Have you ever laughed at a joke that nobody else found funny?",
    "What's the silliest thing that made you cry?",
    "Have you ever mistaken someone for a celebrity?",
    "What's the most ridiculous excuse you've given to get out of something?",
    "Have you ever laughed so hard that you snorted?",
    "What's the weirdest thing you've Googled recently?",
    "Have you ever had a laugh attack in a quiet place like a library or church?",
    "What's the silliest way you've injured yourself?",
    "Have you ever been caught taking a selfie?",
    "What's the funniest text message you've received from a family member?",
    "Have you ever laughed uncontrollably during a serious conversation?",
    "What's the most embarrassing thing you've posted on social media?",
    "Have you ever had an awkward encounter with your boss?",
    "What's the strangest thing you've eaten for a dare?",
    "Have you ever laughed at your own joke when no one else did?",
    "What's the funniest thing you've seen a pet do?",
    "Have you ever fallen asleep during an important meeting or class?",
    "What's the silliest thing you've done to impress someone?",
    "Have you ever laughed at a funeral or memorial service?",
    "What's the most ridiculous purchase you've made online?",
    "Have you ever laughed at a serious news article headline?",
    "What's the oddest place you've found something you lost?",
    "Have you ever accidentally sent a voice message to the wrong person?",
    "What's the funniest autocorrect fail you've experienced?",
    "Have you ever laughed at a book or a comic strip in a library?",
    "What's the most absurd thing you've done when nobody was looking?",
    "Have you ever laughed so hard that you snorted in front of your crush?",
    "What's the silliest superstition you believe in?",
    "Have you ever laughed so hard that you cried in a public place?",
    "What's the most ridiculous thing you've done on a dare?",
    "Have you ever laughed at something inappropriate during a serious conversation?",
    "What's the funniest dream you've ever had?",
    "Have you ever mistaken a stranger for someone you knew and started a conversation?",
    "What's the silliest thing you've said while half-asleep?",
    "Have you ever laughed at a movie that was supposed to be sad?",
    "What's the most absurd thing you've done to avoid a bug or insect?",
    "Have you ever laughed at a YouTube video so hard that you had to replay it multiple times?",
    "What's the funniest sound you can imitate?",
    "Have you ever laughed so hard that you fell off your chair?",
    "What's the silliest thing you've done to avoid talking to someone you didn't want to?",
    "Have you ever laughed at a pun that nobody else found funny?",
    "What's the most ridiculous thing you've laughed at while in a library or bookstore?",
    "Have you ever mistaken a statue or mannequin for a real person?",
    "What's the funniest thing you've seen a child do?",
    "Have you ever laughed at a video call glitch or technical issue?",
    "What's the silliest way you've embarrassed yourself in front of a celebrity?",
    "Have you ever laughed at your own reflection in a mirror?",
    "What's the most absurd thing you've done to impress your crush?",
    "Have you ever laughed so hard at a joke that you snorted while eating or drinking?",
    "What's the funniest thing you've seen a baby do?",
    "Have you ever laughed at a situation that was supposed to be serious?",
    "What's the silliest thing you've done when you thought you were alone?",
    "Have you ever mistaken someone's twin or doppelganger for them?",
    "What's the most ridiculous thing you've laughed at during a lecture or presentation?",
    "Have you ever laughed at a movie character's facial expression?",
    "What's the funniest thing you've seen a stranger do in public?",
    "Have you ever laughed at a funny text message while in a meeting?",
    "What's the silliest way you've tried to avoid a bug or insect?",
    "Have you ever laughed at a joke that nobody else understood?",
    "What's the most absurd thing you've done on a dare in a public place?",
    "Have you ever laughed so hard that you cried during a serious discussion?",
    "What's the funniest thing you've seen a pet do in front of guests?",
    "Have you ever laughed at a TV commercial or advertisement?",
    "What's the silliest thing you've done to entertain yourself when you were bored?",
]

TH = [
    "kya aapane kabhee galatee se galat vyakti ko koee sandesh bheja hai?",
    "veediyo kol ke dauraan aapane sabase moorkhataapoorn kaam kya kiya hai?",
    "kya aap kabhee kisee gambheer meeting mein meem par hansate hue pakade gae hain?",
    "jab koee nahin dekh raha ho to aapaka daans moov kya hai?",
    "kya aapane kabhee hansate samay kharraate lee hai?",
    "aap kis ajeeb bhojan sanyojan ka aanand lete hain?",
    "kya aapane kabhee shovar mein gaana gaaya hai aur dikhaava kiya hai ki aap kisee sangeet veediyo mein hain?",
    "aapake lie sabase sharmanaak svat: sudhaar viphalata kya hai?",
    "kya aap kabhee itanee zor se hanse hain ki roye hain?",
    "aapaka ab tak ka sabase ajeeb sapana kya hai?",
    "kya aapane kabhee kisee selibritee kataut ke saath selphee lene kee koshish kee hai?",
    "aapane ab tak kaun see sabase majedaar philm ya teevee sho dekha hai?",
    "kya tumane kabhee galatee se apane kapade ulate pahane hain?",
    "aapane sabase haasyaaspad phaishan trend kya apanaaya hai?",
    "kya aapane kabhee kisee geet ko jaanane ka naatak kiya hai jab aapako geet ke bolon ke baare mein koee jaanakaaree nahin thee?",
    "kisee ajanabee ke saath aapakee sabase ajeeb muthabhed kya hai?",
    "kya aapane kabhee soshal meediya par kisee ko stok karate samay galatee se koee puraanee tasveer laik kar dee hai?",
    "aapane ab tak dekha sabase mazedaar youtubai veediyo kaun sa hai?",
    "kya aap kabhee kisee aise chutakule par hanse hain jo aapako samajh mein nahin aaya ho?",
    "bachapan mein aap kis sabase moorkhataapoorn cheez par vishvaas karate the?",
    "kya aap kabhee itanee zor se hanse hain ki aap saans nahin le sake?",
    "aapane apane krash ke saamane sabase sharmanaak kaam kya kiya hai?",
    "kya aapane kabhee apane krash ko galatee se koee tekst bheja hai?",
    "aapaka sabase sharmanaak upanaam kya hai?",
    "kya aap kabhee kisee gambheer kshan ke dauraan kisee anuchit baat par hanse hain?",
    "aapake paas sabase ajeeb pratibha kya hai?",
    "kya aap kabhee saarvajanik sthaan par ladakhadaakar gire hain?",
    "aapane jaanavaron ka sabase majedaar veediyo kaun sa onalain dekha hai?",
    "kya aapane kabhee kisee selibritee ke uchchaaran kee nakal karane kee koshish kee hai?",
    "aapake brauzar itihaas mein sabase sharmanaak baat kya hai?",
    "kya aap kabhee kisee gambheer bahas ke dauraan hanse hain?",
    "jab aap akele hote hain to aapakee sabase ajeeb aadat kya hotee hai?",
    "kya aapane kabhee anajaane mein kisee ka apamaan kiya hai?",
    "aap kaun sa sabase mazedaar shabd jaanate hain?",
    "kya aapakee kabhee saarvajanik parivahan par kisee ajanabee se ajeeb muthabhed huee hai?",
    "aapane kaun see sabase ajeeb cheez ekatr kee hai?",
    "kya aap kabhee kisee aise chutakule par hanse hain jo kisee aur ko mazaakiya na laga ho?",
    "vah kaun see moorkhataapoorn baat hai jisane aapako rula diya?",
    "kya aapane kabhee kisee ko galatee se selibritee samajh liya hai?",
    "kisee cheez se baahar nikalane ke lie aapane sabase haasyaaspad bahaana kya diya hai?",
    "kya aap kabhee itanee jor se hanse hain ki aapakee naak mein dam ho gaya?",
    "haal hee mein aapane googal par sabase ajeeb cheez kya khojee hai?",
    "kya aapako kabhee laibreree ya charch jaisee shaant jagah par hansee ka daura pada hai?",
    "aapane khud ko kis moorkhataapoorn tareeke se ghaayal kiya hai?",
    "kya aap kabhee selphee lete hue pakade gae hain?",
    "aapako parivaar ke kisee sadasy se praapt hua sabase mazedaar tekst sandesh kaun sa hai?",
    "kya aap kabhee kisee gambheer baatacheet ke dauraan aniyantrit roop se hanse hain?",
    "aapane soshal meediya par sabase sharmanaak baat kya post kee hai?",
    "kya aapaka kabhee apane bos ke saath ajeeb saamana hua hai?",
    "aapane himmat karake kaun see sabase ajeeb cheez khaee hai?*",
    "kya aap kabhee apane hee chutakule par hanse hain jabaki koee aur nahin hansa?",
    "aapane kisee paalatoo jaanavar ko sabase mazedaar cheez kya karate dekha hai?",
    "kya aap kabhee kisee mahatvapoorn baithak ya kaksha ke dauraan so gae hain?",
    "kisee ko prabhaavit karane ke lie aapane sabase moorkhataapoorn kaam kya kiya hai?",
    "kya aap kabhee kisee antim sanskaar ya smaarak seva mein hanse hain?",
    "aapane onalain jo sabase haasyaaspad khareedaaree kee hai vah kya hai?",
    "kya aap kabhee kisee gambheer samaachaar lekh ke sheershak par hanse hain?",
    "sabase ajeeb jagah kaun see hai jahaan aapako koee khoee huee cheez milee?",
    "kya aapane kabhee galatee se galat vyakti ko dhvani sandesh bheja hai?",
    "sabase mazedaar svat: sudhaar viphalata kya hai jise aapane anubhav kiya hai?",
    "kya aap kabhee laibreree mein kisee kitaab ya komik strip par hanse hain?",
    "jab koee nahin dekh raha tha to aapane sabase betuka kaam kya kiya?",
    "kya aap kabhee itana hanse hain ki apane krash ke saamane kharraate lene lage?",
    "aap kis moorkhataapoorn andhavishvaas par vishvaas karate hain?",
    "kya aap kabhee itana hanse hain ki saarvajanik sthaan par ro pade?",
    "aapane himmat karake sabase haasyaaspad kaam kya kiya hai?",
    "kya aap kabhee gambheer baatacheet ke dauraan kisee anuchit baat par hanse hain?",
    "aapaka ab tak ka sabase mazedaar sapana kya hai?",
    "kya aapane kabhee kisee ajanabee ko galatee se koee aisa vyakti samajh liya hai jise aap jaanate hain aur usase baatacheet shuroo kar dee hai?",
    "aapane aadhee neend mein kya sabase moorkhataapoorn baat kahee hai?",
    "kya aap kabhee kisee aisee philm par hanse hain jise dukhad maana jaata tha?",
    "kisee keede ya keede se bachane ke lie aapane sabase betuka kaam kya kiya hai?",
    "kya aap kabhee kisee youtubai veediyo par itana hanse hain ki aapako use kaee baar doharaana pada?",
    "sabase mazedaar dhvani kaun see hai jisaka aap anukaran kar sakate hain?",
    "kya aap kabhee itanee zor se hanse ki aap apanee kursee se gir gae?",
    "aapane kisee aise vyakti se baat karane se bachane ke lie sabase moorkhataapoorn kaam kya kiya hai, jisase aap baat nahin karana chaahate?",
    "kya aap kabhee kisee aise vaaky par hanse hain jo kisee aur ko mazaakiya na laga ho?",
    "laibreree ya kitaabon kee dukaan mein aap kis sabase haasyaaspad cheez par hanse hain?",
    "kya aapane kabhee kisee moorti ya putale ko vaastavik vyakti samajh liya hai?",
    "aapane kisee bachche ko sabase mazedaar cheez kya karate dekha hai?",
    "kya aap kabhee kisee veediyo kol mein gadabadee ya takaneekee samasya par hanse hain?",
    "kisee selibritee ke saamane aapane khud ko sharminda karane ka sabase moorkhataapoorn tareeka kya hai?",
    "kya aap kabhee darpan mein apana pratibimb dekhakar hanse hain?",
    "aapane apane krash ko prabhaavit karane ke lie sabase betuka kaam kya kiya hai?",
    "kya aap kabhee kisee chutakule par itana hanse hain jitana khaate ya peete samay kharraate lete the?",
    "aapane kisee bachche ko sabase mazedaar cheez kya karate dekha hai?",
    "kya aap kabhee aisee sthiti par hanse hain jo gambheer maanee jaatee ho?",
    "jab aapane socha ki aap akele hain to aapane sabase moorkhataapoorn kaam kya kiya?",
    "kya aapane kabhee kisee ke judavaan ya hamashakl ko galatee se samajha hai?",
    "vyaakhyaan ya prastuti ke dauraan aap kis sabase haasyaaspad cheez par hanse hain?",
    "kya aap kabhee kisee film ke paatr ke chehare ke haav-bhaav par hanse hain?",
    "aapane kisee ajanabee ko saarvajanik roop se kya karate hue sabase mazedaar cheez kya dekhee hai?",
    "kya aap kabhee kisee meeting ke dauraan kisee mazaakiya tekst sandesh par hanse hain?",
    "kisee keede ya keede se bachane ka aapane kaun sa moorkhataapoorn tareeka apanaaya hai?",
    "kya aap kabhee kisee aise chutakule par hanse hain jise koee aur nahin samajh paaya?",
    "saarvajanik sthaan par aapane jo sabase betuka kaam kiya hai vah kya hai?",
    "kya aap kabhee kisee gambheer charcha ke dauraan itanee zor se hanse ki ro pade?",
    "aapane kisee paalatoo jaanavar ko mehamaanon ke saamane sabase mazedaar cheez kya karate dekha hai?",
    "kya aap kabhee kisee teevee vigyaapan ya vigyaapan par hanse hain?",
    "jab aap bor ho rahe the to apana manoranjan karane ke lie aapane sabase moorkhataapoorn kaam kya kiya?",
]
